### ISSUE TITLE
Cannot get to work with TOTP

### ISSUE THREAD

**Issue by iainsmacleod** [romedtino/simple-wyze-vac#37]
I removed Wyze 2FA and got the app to work fine, however I prefer to have it enabled. When reenabling, and copying the base32 code, I was unable to get the Simple Vacuum integration to work.

2022-06-22 20:09:44 ERROR (MainThread) [custom_components.simple_wyze_vac.config_flow] Failed to login Wyze servers.

**Comment by romedtino** [comment]
Perhaps the Wyze servers were down when you tried this? Have you tried it again?

I just tried it on my account with a fresh 2FA setup and it worked. Make sure you follow the order of sequences here - https://github.com/romedtino/simple-wyze-vac#totp

Specifically, the part where you copy the Base32 code, set it up on your Authenticator account, then setup Simple Wyze Vac with that same Base32 code **NOT** the TOTP 6 digits from the Authenticator you use.

**Comment by iainsmacleod** [comment]
Tried it several times. I'm reluctant to reset the code again, as I have a
lot of automation and scenes around wyze cameras, and it will lose it when
I redo the process.

**Comment by iainsmacleod** [comment]
I just reset my 2FA to try this again. Copied and pasted the recovery code. Used my username and password to log in, and it just errors.

**Comment by romedtino** [comment]
It's not the recovery code you copy and paste, it's the base32 code you get that you're supposed to put in the Authenticator.

Here's a screenshot of that value you will need to copy when setting up Simple Wyze Vac

![image](https://user-images.githubusercontent.com/18567128/179343369-18c38381-0151-45e7-84ec-494f7c8ab6f1.png)

and the excerpt from the TOTP steps I outlined

```
Read the instructions from Wyze BUT make sure to copy and KEEP the value in step 3. This is your Base32 SECRET used to generate TOTP.
```

This is also the same key you would put in the Authenticator app. Depending on which you setup first, you can induce an error in Home Assistant but as long as you setup both the Authenticator and Home Assistant, it should still login. e.g. If you grab the Base32 code first and put it in Simple Wyze Vac with your username and password, it will show an error in the log (this is because you haven't setup your Authenticator yet.) But once you finish setting up your Authenticator and finish the Wyze 2FA setup, the login on Simple Wyze Vac should work.

**Comment by iainsmacleod** [comment]
I apologize. I did not follow that at all. I will try again. Many thanks!

**Comment by iainsmacleod** [comment]
It worked! Thank you for your patience.

**Comment by romedtino** [comment]
Sounds good, glad you got it working!
