### ISSUE TITLE
After installing do not see rooms or built-in services

### ISSUE THREAD

**Issue by sssanderson** [romedtino/simple-wyze-vac#41]
After installing, I see my vacuum and I am able to run a FULL clean and dock sweep power setting, etc. But can't see rooms or the built-in service and choose the switch entities/rooms you want to do a sweep. 

What needs to be done and where to enable these features?

**Comment by romedtino** [comment]
Having the selected room vacuum feature are dependent on the firmware version of your Wyze vacuum. If you're on the release version - `1.6.113`, it should work. Anything above that is currently unsupported since these are beta firmware versions (and has model changes to accommodate for multi-floor vacuuming).

I think shauntarves, the creator of `wyze-sdk` actually has a beta version of his SDK that could work on these beta firmwares (https://github.com/romedtino/simple-wyze-vac/issues/27#issuecomment-1129347058). But until that's been fully vetted, I'm hesitant to add it to Simple Wyze Vac. 

If anyone is tech savvy enough to install that version of `wyze-sdk` and have it run against the lastest version of `simple-wyze-vac` and see if it works, I'd be glad to update/PR the changes. I'm not really willing to switch to the beta version of the vacuum especially since there's no easy way to downgrade.

**Comment by RickSisco** [comment]
So this integration is no longer working after 1.6.113 and we are currently on 1.6.306

**Comment by romedtino** [comment]
I think this should be addressed on the latest simple wyze vac
